#!/bin/bash
# Heroku CLI Commands to Fix Deployment

APP_NAME="daniyalportfolio-4bc9ee1ed36d"

echo "🔧 Heroku Setup Commands"
echo "========================"
echo ""
echo "1️⃣  Login to Heroku:"
echo "   heroku login"
echo ""
echo "2️⃣  Connect to your app:"
echo "   heroku git:remote -a $APP_NAME"
echo ""
echo "3️⃣  Check current config:"
echo "   heroku config -a $APP_NAME"
echo ""
echo "4️⃣  View logs:"
echo "   heroku logs --tail -a $APP_NAME"
echo ""
echo "5️⃣  Check dyno status:"
echo "   heroku ps -a $APP_NAME"
echo ""
echo "6️⃣  Restart dyno:"
echo "   heroku restart -a $APP_NAME"
echo ""
echo "7️⃣  Initialize database (after env vars set):"
echo "   heroku run python3 backend/scripts/setup_db.py -a $APP_NAME"
echo ""
echo "8️⃣  Open app:"
echo "   heroku open -a $APP_NAME"
echo ""
echo "📝 Note: Files in root are minimal (Procfile, requirements.txt, .python-version)"
echo "   Actual app code is in backend/ directory"
