[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "pip install --break-system-packages uvicorn",
  "pip install --break-system-packages -r backend/requirements.txt"
]

[phases.build]
cmds = ["echo 'Python backend build complete'"]

[start]
cmd = "./start.sh"
