[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --user --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend build complete'"]

[start]
cmd = "python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
