[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend build complete'"]

[start]
cmd = "cd backend && python -c 'import uvicorn, os; uvicorn.run(\"app.main:app\", host=\"0.0.0.0\", port=int(os.environ[\"PORT\"]))'"
